export const PermissionCodes = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  MAINMENU_VIEW: 'MAINMENU_VIEW',

  PROFILE_VIEW: 'PROFILE_VIEW',
  PROFILE_EDIT: 'PROFILE_EDIT',
  PROFILE_PASSWORD_CHANGE: 'PROFILE_PASSWORD_CHANGE',

  ADMIN_USER_VIEW: 'ADMIN_USER_VIEW',
  ADMIN_USER_EDIT: 'ADMIN_USER_EDIT',
  ADMIN_USER_RESET_PASSWORD: 'ADMIN_USER_RESET_PASSWORD',
  ADMIN_USER_LOCK: 'ADMIN_USER_LOCK',
  ADMIN_USER_UNLOCK: 'ADMIN_USER_UNLOCK',

  ADMIN_PERMISSION_VIEW: 'ADMIN_PERMISSION_VIEW',
  ADMIN_PERMISSION_EDIT: 'ADMIN_PERMISSION_EDIT',
  ADMIN_ROLE_PERMISSION_VIEW: 'ADMIN_ROLE_PERMISSION_VIEW',
  ADMIN_ROLE_PERMISSION_EDIT: 'ADMIN_ROLE_PERMISSION_EDIT',
  ADMIN_USER_PERMISSION_VIEW: 'ADMIN_USER_PERMISSION_VIEW',
  ADMIN_USER_PERMISSION_EDIT: 'ADMIN_USER_PERMISSION_EDIT',

  WORKFLOW_DEFINITION_VIEW: 'WORKFLOW_DEFINITION_VIEW',
  WORKFLOW_DEFINITION_EDIT: 'WORKFLOW_DEFINITION_EDIT',
  WORKFLOW_INSTANCE_VIEW: 'WORKFLOW_INSTANCE_VIEW',
  WORKFLOW_INSTANCE_START: 'WORKFLOW_INSTANCE_START',
  WORKFLOW_INSTANCE_ACTION: 'WORKFLOW_INSTANCE_ACTION',
  WORKFLOW_INSTANCE_CANCEL: 'WORKFLOW_INSTANCE_CANCEL',
  WORKFLOW_INSTANCE_RETURN: 'WORKFLOW_INSTANCE_RETURN',
  WORKFLOW_INSTANCE_HOLD: 'WORKFLOW_INSTANCE_HOLD',
  WORKFLOW_TASK_VIEW: 'WORKFLOW_TASK_VIEW',
  WORKFLOW_TASK_ACTION: 'WORKFLOW_TASK_ACTION',
  WORKFLOW_REPORT_VIEW: 'WORKFLOW_REPORT_VIEW',

  MINI_PRODUCTION_VIEW: 'MINI_PRODUCTION_VIEW',
  MINI_PRODUCTION_CREATE: 'MINI_PRODUCTION_CREATE',
  MINI_PRODUCTION_EDIT: 'MINI_PRODUCTION_EDIT',
  MINI_PRODUCTION_SUBMIT: 'MINI_PRODUCTION_SUBMIT',
  MINI_PRODUCTION_CANCEL: 'MINI_PRODUCTION_CANCEL',
  MINI_PRODUCTION_REPORT_VIEW: 'MINI_PRODUCTION_REPORT_VIEW',

  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  REPORT_VIEW: 'REPORT_VIEW',
  MASTER_DATA_VIEW: 'MASTER_DATA_VIEW',
  MASTER_DATA_EDIT: 'MASTER_DATA_EDIT',
  SYSTEM_HEALTH_VIEW: 'SYSTEM_HEALTH_VIEW',
} as const;

export type PermissionCode = typeof PermissionCodes[keyof typeof PermissionCodes];
